networks:
  easy-crit:
    driver: bridge

services:
  db:
    image: bitnami/postgresql:latest
    networks:
      - easy-crit
    restart: always
    environment:
      POSTGRESQL_USERNAME: ${USER}
      POSTGRESQL_PASSWORD: ${PASSWORD} 
      POSTGRESQL_DATABASE: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${AUTH_PORT:-8000} --reload
    volumes:
      - .:/app
    ports:
      - "${AUTH_PORT:-8000}:${AUTH_PORT:-8000}"
    environment:
      - DATABASE_URL="postgresql://${USER}:${PASSWORD}@db:5432/${DB_NAME}"
    depends_on:
      - db

volumes:
  data:
